import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { builtinModules } from "module";
import { fileURLToPath } from "node:url";
import {
	loadObsidianPluginDir,
	syncBuiltMainJs,
	syncStaticAssets,
	watchStaticAssets,
} from "./scripts/obsidianDevSync.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const projectRoot = path.dirname(fileURLToPath(import.meta.url));
const obsidianPluginDir = loadObsidianPluginDir(projectRoot);

const nodeBuiltins = Array.from(
	new Set(
		builtinModules.flatMap((moduleName) =>
			moduleName.startsWith("node:")
				? [moduleName, moduleName.slice("node:".length)]
				: [moduleName, `node:${moduleName}`]
		)
	)
);

if (obsidianPluginDir) {
	console.info(`[smart-export] Syncing build artifacts to ${obsidianPluginDir}`);
	syncStaticAssets(projectRoot, obsidianPluginDir);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...nodeBuiltins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: obsidianPluginDir
		? [
				{
					name: "obsidian-plugin-dir-sync",
					setup(build) {
						build.onEnd((result) => {
							if (result.errors.length > 0) {
								return;
							}

							syncBuiltMainJs(projectRoot, obsidianPluginDir);
						});
					},
				},
			]
		: [],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	const stopWatchingStaticAssets = obsidianPluginDir
		? watchStaticAssets(projectRoot, obsidianPluginDir)
		: () => {};
	process.on("exit", stopWatchingStaticAssets);
	await context.watch();
}
